development:
  adapter: postgresql
  encoding: utf8
  database: rorblog_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: rorblog_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: rorblog_production
  pool: 5
